/**
 * GENERATED by scripts/brand/export-email-logo.mjs from docs/brand/mulemark-lockup.svg. Do not edit by hand; run `npm run brand:email-logo`.
 *
 * Engineering Phase D5.1 — the Mulemark lockup for email headers: a 600×64 PNG on white
 * (2176 bytes), shown at 200×21 px and attached inline to every notification email.
 */
export const EMAIL_LOGO = {
  filename: "mulemark-logo.png",
  contentType: "image/png",
  contentId: "mm-logo@mulemark",
  width: 200,
  height: 21,
  pixelWidth: 600,
  pixelHeight: 64,
  base64: [
    "iVBORw0KGgoAAAANSUhEUgAAAlgAAABABAMAAAA0UhQwAAAAMFBMVEUaGRf///+oeyLS0tHs596wr69ubmz29fQ9PDqIiIfGxsRZ",
    "WFaZmJgrKijTvZG+nFoeOLnFAAAACXBIWXMAABYlAAAWJQFJUiTwAAAH9klEQVR42u2cTWwbRRSAV3Ltru3ksLLXjn+iCvfArdhK",
    "RSVOMe21yJa4InklmgPiUDdItBIBR0gUKAdHHBFSzAkqDo56aEWFZN+Q4JAIUA7cKiTODQckTtjen3nvzZtNnN0xVZQ5rb07szPf",
    "vnnz5s2bMazzdOJknCOYH9Z7N+ZOXa684tosXQV/5dy/rk2vr7vXDe8W/OlernUVJeLUnNzYxGWB8pow/6af5xoLYHbrhqUuJC+y",
    "u7DeOKqdIv3L4Noy3LQj/uq4/5jThu+710mvHuBnycu4rSoRpQuTG0P3MiserYK7fsoHeZabDCvvteatoC057/GE97tvBPWfwfqw",
    "drp0RX75uld0JvjH9isLKpLG9Zr+LHjXF1UlojQtvuddj0NeLj4CelAkH4WRapD6Jkn10y6sXO206R8lLFOWDF2whBwNGVgrItOe",
    "UrBmtJosrJsg97QJz04Nq9ZUNm0sfTtdsLKSDENYddx3VYI1Sb+zsIagExtRBKtWe1nZtAtEBeiDZbSpDGd4HMkwwQr0LIZVhZkn",
    "TXg9AqxXlE3LSt1AG6xDPJJgWD2RKRsqWH6tMKygFzourKMIsGoDZdO87z3SDytFZTjDDYaT1A0VLK/KGJb/ErM7gxWlF9ZqLymb",
    "doisA52wjAaR4YxsTaD+yguWpzoQrBIq0rAuRYJ1Wdk093sXjAXA2iYyDGBVYC4nXLDcfopg7aLxyrDuRIJ1Rd20BnqbTlhLRIYB",
    "rNsw12G4YBnGgMAq4hHXiKTfZQ0PmrYN36YV1sw2LxgcrBbNFSJYriUGYQVl/ubB+iYSrJq6aUukQvpgzfrXLgtlCHOljhGsmdKC",
    "sFpY2xlRTNJp6iqbNv3edU2wLmBYSSzDAlZxH+ZaPkawZt8XwAp6dsqKB1ZT3TQHf9iIsB5RrwOgMxnYS2x3szGMhiRYX04Ke/gT",
    "1PAAVjA63NcPK4kH7oiwHHqjh4zvOgurYDA2OhSsNtJsJoY1IpB1wjK7NxcFK4FkWMBaxbC2JY3VxgLYhbByaLTVDMvY6SwKVrbK",
    "j3q7GFZC0lhtPA40Iay71F2hFdaSsShYxtc8rL6swDHFNn6uAWH1qddQKyxjcbAMHhZ5xpTsrzb+OQCwylJxZxtW8ALQzVhYI0ay",
    "tqRh4WzD8jVTYkRdkq3jdVYHOhxkWH92N49eWFiP33dTdw5YviPioE49yxgWXCfwr03/v18tDtZf0+no0YsKC7voTgYrkMpVWjqG",
    "9RZjlDLrHACW60D46EWHlZ0Dlt/72gXqWfZhTS34136GH4LCSlkcrOfubOoswQpUkU1b3mIzJhhYhywsr9nPzg6sfGAxFH2TqRsK",
    "a5uB1eZg+Z6pO7HAeiJsm55eWMtiovMHgVUV5Q9J03lYbQaWw8HyfZ6XYoH1jhDtoV5YppiA/kJgVcTvEWk6C8tkHBVgigRgXY4V",
    "lhNMCx3dsIJpYXCVIT7lA+FYOwiDleBgZRcA62agJXTDCpRXgsJqCetqVXFLNhJsQ6m0dHVDpxoM1tph1ek7M2TVdSyKT4fASlss",
    "rEPtCt7x27KnH1bBl2ECK/Apg0mMGQJrzMNKazcdHP97N/TD8qAIx6wHqwwAFYnTk4H1scXDErNvXUap47UejNraYHkt36OwUNcb",
    "YheCDOuLrgrWnu7pjuN97/uxw0rJsCqezBBYSKmPsGe5xZoNPKyM7om049VnEBusHx66aSDDynmFEFi7sMg6DoXyYT142iMrP7ah",
    "5KjLRTOBZW9sbNyyYoOl8mdNm/Ld5FVjCVYfdqNV7FkWXod10tkELJP6HXQ5/xx5UVgjLDK9yeDJ4xgqsCyFVSCWuoD19j5avF80",
    "rDyGVQZfO35YwUrWg6eT9CMe2wSsHNGFAazl7ojcWiysIn67rRVWiXdJjKnzj/jnQWTq3QUtsvKwLBx0UGACVuKDtcLD2qOwWvgF",
    "tnA32MR4WDCsfRAIJSJmE1pgKVxrFymsFTxO2sD1NcQO1gXDGiJrpw/qHz+sEQ8rSWFV1bqhjn2GC4bVhxWzoYMyflhDHlaKwoJT",
    "SFUw287/ASuIPXg0GRo7sCp+vTJoQ9MJQo5UsIoKn7MrJXB1p6OMg8/jqH5dwWwKWCKq5ZONIQqbKqj8vMcFs6lg2SoP/YDCWke+",
    "GBSA2ycxpXrCJBWwSkpvLg9r5/gwSRWsigqWQ2FV1JsGthBhXQG4Clh5pcqNHdZtFawDCquMOiiCVUWxf7pCuxWwuKhXd2iMHVYr",
    "dKEMrUj3OLcy3mGxpHPTgArWXZUSiR1WRwUrLcEaQaWFYe3CGK2o21GezwmrrHJ9xw7LNwg+91w7D7+FKhLB2oLig2FV4tzo1JgT",
    "FmMqPtYCqyzFdZTg4ItgleAsDMPKwWUyXVvolLCk8dALf4obVkEK5y5Dsw7BynMr0km8QmRa+jZnKmFJovXY0gJrVYqMDDrmthRy",
    "1GFiHei237a+bb9qWOV9dqEpblh1OWJoCCxaDGsXACKwqmD5UNeGcjUs6x7qhANNsPryXt8R0OMY1gq/acCCW7XS+o4qCIFlvQrW",
    "tdqWJlg9eWK+DuYuijDJtgRL2GvNSIdg/B1yCMZY2ssAGvWBz++zRui+o1nl5zgEwwZ39+WvVgHyU0fqvwjMUnoIRkUMq5qOV1lT",
    "HK/iP/X9V08+ffDum9I5JyRdPcHxKtf4k1GuyxUpgnNW8vgYmE3wND2jRXhAzg/usc5POdIC6z/h056XNTWGxQAAAABJRU5ErkJg",
    "gg==",
  ].join(""),
} as const;
